targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - invalid_annotation_target
      json_serializable:
        options:
          checked: true
          explicit_to_json: true